spring.application.name=Analise de dados via API

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=user
spring.datasource.password=101010

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console